included:
  - Sources
line_length:
  ignores_comments: true
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - file_name_no_space
  - let_var_whitespace
  - literal_expression_end_indentation
  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - pattern_matching_keywords
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_imports
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces
  - yoda_condition
