name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  test:
    runs-on: macos-11
    timeout-minutes: 30
    steps:
      - run: sudo xcode-select --switch /Applications/Xcode_13.2.1.app
      - uses: actions/checkout@v2
      - name: Install xcpretty
        run: gem install xcpretty
      - name: Run Tests
        run: |
          set -eo pipefail
          xcodebuild test \
            -scheme IonicPortals \
            -destination 'platform=iOS Simulator,name=iPhone 13' | xcpretty
        env:
          SWIFTPM_ENABLE_PLUGINS=1
  validate-podspec:
    runs-on: macos-11
    timeout-minutes: 30
    steps:
      - run: sudo xcode-select --switch /Applications/Xcode_13.2.1.app
      - uses: actions/checkout@v2
      - name: Install cocoapods
        run: gem install cocoapods
      - name: Lint Podspect
        run: pod lib lint
  lint:
    runs-on: macos-12
    steps:
      - run: sudo xcode-select --switch /Applications/Xcode_14.1.app
      - uses: actions/checkout@v2
      - name: Run Swiftlint
        run: swift run swiftlint --strict
